version: '3.8'

services:

  app:
    build: .
    image: node:18
    container_name: node-url-shortener-app
    ports:
      - "3000:3000"  # Expose your app on port 3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis  # Use the latest stable Redis image
    container_name: redis-container
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
